### ISSUE TITLE
Flink Demo Package Verify Error

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/frameworks#133]
go run cmd/kubectl-kudo/main.go package verify ../operators/repository/flink/docs/demo/financial-fraud/demo-operator/
Errors                                                           
parameter "download_url" in template uploader.yaml is not defined
Error: package verification errors: 1
exit status 255

**Comment by fabianbaier** [comment]
Format changed :)

```apiVersion: kudo.dev/v1beta1
parameters:
 - name: download_url
   description: URL To download the application from
   default: "https://downloads.mesosphere.com/dcos-demo/flink/flink-job-1.0.jar"
   displayName: "Download URL"
```

should do the trick for the `params.yaml` - will you do the PR for it or should I do it?
