### ISSUE TITLE
Update or remove outdated demos

### ISSUE THREAD

**Issue by nfnt** [kudobuilder/frameworks#154]
Demos are broken or outdated. E.g. the Flink financial fraud demo is supposed to use KUDO 0.7 according to its `README`. But the operator only works on KUDO 0.8 though, while depending on packages that only work on KUDO 0.7.
The Flink modifications demo doesn't use operator packages at all.

These demos need to be updated or removed.

**Comment by nfnt** [comment]
Then Flink financial fraud demo has been updated to work with KUDO 0.8 in https://github.com/kudobuilder/operators/pull/155.

**Comment by guenter** [comment]
Closing because the Flink demo has been fixed. If others are broken too please open a new PR.
