### ISSUE TITLE
[kafka] move away from gcr.io/google-samples image

### ISSUE THREAD

**Issue by zmalik** [kudobuilder/frameworks#16]
We are using a `gcr.io/google-samples` images for kafka operator. 

The `gcr.io/google-samples` is a stalled image and there are more issues to that image other than being stalled.

ref: https://github.com/helm/charts/issues/4540

We should replace the image with a community supported image that is as close to apache/kafka configuration and without tweaks done for a specific platform.

**Comment by fabianbaier** [comment]
Agreed, I think we have the same notion in our `Zookeeper` Framework as well. I would propose we look first how other communities solve this, e.g. Helm/Bitnami before we settle for a decision. 

On the top of my head...
I don't see KUDO in the business of building Docker containers or replicas of existing ones, so we need to be careful on what we decide here. Ideally, we adapt those that the community gravitates the most to.

**Comment by zmalik** [comment]
`helm` is using the confluent community flavor of Kafka
`bitnami` is using their own image 

I agree that Kudo should be really careful around building new container images, but in this case, we have only opinionated flavors of Kafka containers.

`bitnami` is really keeping up with upstream kafka releases but they are:
- based on their own images e.g `bitnami/minideb-extras:stretch-r360`
- have some defaults that need to be stripped out carefully e.g broker `user/pass` to `user/bitnami`, inter-broker `user/pass` defaults to `admin/bitnami`

**Comment by zmalik** [comment]
other operators are also building their own images
e.g just discovered this through kafka user list: https://github.com/strimzi/strimzi-kafka-operator/blob/master/docker-images/kafka/Dockerfile

**Comment by zmalik** [comment]
was fixed by https://github.com/kudobuilder/operators/pull/29
