### ISSUE TITLE
New Repo Structure

### ISSUE THREAD

**Issue by fabianbaier** [kudobuilder/frameworks#17]
**What would you like to be added:**

I'd like to add a new more flatter structure that reflects more changes for KUDO `0.2.0` that will break the current structure. Breaking it should be fine as we are still under `1.0.0`.

Proposed structure:

```
/.github
/.circleci
/docs
/hack
/repository
/repository/index.yaml
/repository/kafka
/repository/kafka/0.2.0
/repository/kafka/0.2.0/kafka-framework.yaml
/repository/kafka/0.2.0/kafka-frameworkversion.yaml
/repository/kafka/0.2.0/kafka-instance.yaml
/repository/kafka/0.2.0/metadata.yaml
/repository/kafka/0.1.0
/repository/kafka/docs
/repository/kafka/docs/README.md
/repository/kafka/docs/Demo.md
/repository/kafka/tests
/repository/kafka/tests/foobar.yaml
/repository/kafka/tests/0.2.0/bar.yaml
/repository/kafka/tests/0.1.0/foo.yaml
/repository/zookeeper
/README.md
```

**Why is this needed:**

We need to change this repo structure so it will work with changes coming from [KEP-0008](https://github.com/kudobuilder/kudo/blob/master/keps/0008-framework-testing.md), [KEP-0009](https://github.com/kudobuilder/kudo/blob/master/keps/0009-operator-toolkit.md)  and [KEP-0010](https://github.com/kudobuilder/kudo/pull/248). This also relates to:
- https://github.com/kudobuilder/kudo/issues/273 
- https://github.com/kudobuilder/kudo/issues/269 
- https://github.com/kudobuilder/kudo/issues/303

**Comment by gerred** [comment]
This looks good to me!
