### ISSUE TITLE
Demo in blog "Running Apache Flink on Kubernetes with KUDO" did not work

### ISSUE THREAD

**Issue by klion26** [kudobuilder/frameworks#172]
I'm following the steps in the flink blog [Running Apache Flink on Kubernetes with KUDO](https://flink.apache.org/news/2019/12/09/flink-kubernetes-kudo.html), 
after execute the command `kubectl kudo plan status --instance flink-demo3`, the output said that "No plan ever run for instance - nothing to show for instance flink-demo3"

I'v installed from the local yaml file using the command ` kubectl kudo install repository/flink/docs/demo/financial-fraud/demo-operator --instance flink-demo3`
and the command outputed
```
repository/flink/docs/demo/financial-fraud/demo-operator is a local file package
instance.kudo.dev/v1beta1/flink-demo3 created
```

anybody can help me with this?

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

minikube version
```
minikube version: v1.6.1
commit: 42a9df4854dcea40ec187b6b8f9a910c6038f81a
```

kubectl kudo version
```
KUDO Version: version.Info{GitVersion:"0.9.0", GitCommit:"9981ed2b", BuildDate:"2019-12-17T17:27:52Z", GoVersion:"go1.13", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by guenter** [comment]
Hi @klion26, the demo in this repo has been fixed: https://github.com/kudobuilder/operators/tree/master/repository/flink/docs/demo/financial-fraud
Let us know if you're still having trouble. Fix for Flink Blog will follow shortly.

**Comment by guenter** [comment]
Flink web PR for reference: apache/flink-web#293
