### ISSUE TITLE
CICD Pipeline to publish repo

### ISSUE THREAD

**Issue by fabianbaier** [kudobuilder/frameworks#18]
**What would you like to be added:**

We should start thinking about for future releases how Frameworks can be updated and published to our official repo and Google Cloud Storage. E.g. how new PRs can be tested with CircleCI and how merges into master will be published to our hosted bucket.

**Why is this needed:**

Right now this is a manual process and fairly slow. Automating this has all known benefits of making it more stable, predictable, etc..

This also relates to:

- https://github.com/kudobuilder/kudo/issues/303

**Comment by nfnt** [comment]
Closing this as this is provided by https://github.com/kudobuilder/operators-index.
