### ISSUE TITLE
RabbitMQ Package Failure

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/frameworks#237]
go run cmd/kubectl-kudo/main.go package create --destination ~/repo ../operators/repository/rabbitmq/operator/
Errors                                                         
plan "not-allowed" used in parameter "DISK_SIZE" is not defined
Error: found 1 package verification errors
exit status 255

**Comment by alenkacz** [comment]
Already fixed in https://github.com/kudobuilder/operators/pull/283
