### ISSUE TITLE
advertised.listeners is not set EXTERNAL_INGRESS when Kafka instance with external NodePort service exposed 

### ISSUE THREAD

**Issue by walk1ng** [kudobuilder/frameworks#267]
Hi guys,

reference the doc: https://github.com/kudobuilder/operators/blob/master/repository/kafka/docs/latest/external-access.md
I installed a Kafka instance with external NodePort type service exposed in my k8s cluster.
```bash
-p EXTERNAL_ADVERTISED_LISTENER=true \
-p EXTERNAL_ADVERTISED_LISTENER_TYPE=NodePort \
```
I exec to the kafka pod inside and check the server.properties as below:
```bash
kafka@kfk-x102-kafka-0:/opt/kafka$ cat server.properties | grep listen
listeners=INTERNAL://0.0.0.0:9093,CLIENT://0.0.0.0:9092
advertised.listeners=INTERNAL://kfk-x102-kafka-0.kfk-x102-svc.x102.svc.cluster.local:9093,CLIENT://kfk-x102-kafka-0.kfk-x102-svc.x102.svc.cluster.local:9092
listener.security.protocol.map=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
inter.broker.listener.name=INTERNAL
```

Expected:
`EXTERNAL_INGRESS` is configured as below(example from above reference):
```bash
advertised.listeners=INTERNAL://kafka-kafka-2.kafka-svc.default.svc.cluster.local:9093,EXTERNAL_INGRESS://34.214.27.71:30904
```

Any mistake or misconfiguration I make here? could you please help.
Thanks a lot!

**Comment by zmalik** [comment]
@walk1ng thanks for the issue, can you please provide the KUDO and KUDO Kafka versions?

**Comment by walk1ng** [comment]
> @walk1ng thanks for the issue, can you please provide the KUDO and KUDO Kafka versions?

Version information:

**KUDO Version**
version.Info{GitVersion:"0.13.0", GitCommit:"900ca042", BuildDate:"2020-05-14T18:23:50Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}

**Operator version**
kafka-1.3.0       
zookeeper-0.3.0

**App version**
kafka 2.5.0
zookeeper 3.4.14

**Comment by zmalik** [comment]
versions seems correct, and it's working as for me but that depends on the kubernetes distro also 
can you verify if the node has an external-ip? 
`kubectl get nodes -o wide` should be enough to verify that and `34.214.27.71` should be listed there 

other things that might help is to check if plans are complete 
```
 kubectl kudo plan status --instance=kafka-instance
```
the external access via nodeports works in KUDO Kafka by using a clusterrole that let the KUDO Kafka get the nodes information and fetch their external-ip. 
if external IP is there you can verify the clusterrole is created correctly 
```
kubectl get clusterrole kafka-instance-clusterrole -o yaml
```

**Comment by zmalik** [comment]
@walk1ng can you test by updating the instance with `-p EXTERNAL_ADVERTISED_LISTENER=false` and enable it again? 
```
kubectl kudo update --instance=kafka-instance  -p EXTERNAL_ADVERTISED_LISTENER=false
```

```
kubectl kudo update --instance=kafka-instance  -p EXTERNAL_ADVERTISED_LISTENER=true
```
it could be an issue with deploy plan

**Comment by walk1ng** [comment]
> -p EXTERNAL_ADVERTISED_LISTENER=false



> versions seems correct, and it's working as for me but that depends on the kubernetes distro also
> can you verify if the node has an external-ip?
> `kubectl get nodes -o wide` should be enough to verify that and `34.214.27.71` should be listed there
> 
> other things that might help is to check if plans are complete
> 
> ```
>  kubectl kudo plan status --instance=kafka-instance
> ```
> 
> the external access via nodeports works in KUDO Kafka by using a clusterrole that let the KUDO Kafka get the nodes information and fetch their external-ip.
> if external IP is there you can verify the clusterrole is created correctly
> 
> ```
> kubectl get clusterrole kafka-instance-clusterrole -o yaml
> ```

my node has not an external-ip, does it the reason I met the problem?
and I checked the deploy plan is COMPLETE.
the clusterrole related my Kafka instance is created.

**Comment by zmalik** [comment]
> my node has not an external-ip, does it the reason I met the problem?

yes @walk1ng, to have any external-access through nodeport it goes through the kubernetes node external-ip

**Comment by walk1ng** [comment]
> > my node has not an external-ip, does it the reason I met the problem?
> 
> yes @walk1ng, to have any external-access through nodeport it goes through the kubernetes node external-ip

question: 
I haven't find the related script or code to add/generate `EXTERNAL_INGRESS://IP:NODEPORT` for `advertised.listeners` property in file `server.properties` if my node have external-ip and I install Kafka with params as below:
```bash
-p EXTERNAL_ADVERTISED_LISTENER=true \
-p EXTERNAL_ADVERTISED_LISTENER_TYPE=NodePort \
```

could you please figure out?

my purpose is create a Kafka cluster with NodePort type services exposed in my k8s, and my apps or users inside of my k8s cluster can access the Kafka and use it.
how can I achieve it with KUDO Kafka operator?

thanks a lot!

**Comment by zmalik** [comment]
@walk1ng have you tested what I posted above? 
https://github.com/kudobuilder/operators/issues/267#issuecomment-634632457
There might be an issue that we need to fix around first time deploys the PR is open https://github.com/kudobuilder/operators/pull/268

**Comment by walk1ng** [comment]
> @walk1ng have you tested what I posted above?
> [#267 (comment)](https://github.com/kudobuilder/operators/issues/267#issuecomment-634632457)
> There might be an issue that we need to fix around first time deploys the PR is open #268

hi zmalik,
I saw your fix had been merged into master.
I tested it follow your comment, firstly update `EXTERNAL_ADVERTISED_LISTENER=false` then update `EXTERNAL_ADVERTISED_LISTENER=true`, I saw the plan `external-access` is COMPLETE.

below is snippet about advertised.listeners in kafka pod.
```bash
kafka@kfk-xyz-kafka-0:/opt/kafka$ cat server.properties | grep listen
listeners=INTERNAL://0.0.0.0:9093,CLIENT://0.0.0.0:9092
advertised.listeners=INTERNAL://kfk-xyz-kafka-0.kfk-xyz-svc.xyz.svc.cluster.local:9093,CLIENT://kfk-xyz-kafka-0.kfk-xyz-svc.xyz.svc.cluster.local:9092
listener.security.protocol.map=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
inter.broker.listener.name=INTERNAL
```

my question is that, if my k8s node has not external-ip configured(I am not the administrator of k8s cluster), any work around to let NodePort service exposed and work?(cannot use loadbalancer also)

thanks for your help and patiences.

**Comment by zmalik** [comment]
>I saw your fix had been merged into master.

it's not yet released, and we will release in upcoming days, as for now the workaround is https://github.com/kudobuilder/operators/issues/267#issuecomment-634632457 for the first time deploys to force the detection of external-ip again 

>my question is that, if my k8s node has not external-ip configured(I am not the administrator of k8s cluster), any workaround to let NodePort service exposed and work? (cannot use loadbalancer also)

How are any services in the cluster exposed outside the kubernetes cluster? I'm afraid that you would need to fix that part before focussing on Kafka itself.

**Comment by Jamlee** [comment]
Cloud i fix it by get the ip value use "internal ip" ?  in private network in company, internal ip is safe  and accessible too.

**Comment by walk1ng** [comment]
could you figure out where

Line#95 to #110 from https://github.com/kudobuilder/operators/blob/master/repository/kafka/operator/templates/bootstrap.yaml 



> > I saw your fix had been merged into master.
> 
> it's not yet released, and we will release in upcoming days, as for now the workaround is [#267 (comment)](https://github.com/kudobuilder/operators/issues/267#issuecomment-634632457) for the first time deploys to force the detection of external-ip again
> 
> > my question is that, if my k8s node has not external-ip configured(I am not the administrator of k8s cluster), any workaround to let NodePort service exposed and work? (cannot use loadbalancer also)
> 
> How are any services in the cluster exposed outside the kubernetes cluster? I'm afraid that you would need to fix that part before focussing on Kafka itself.

hi,
could you please figure out where is the code to create/generate the two files: `/opt/kafka/external.listeners` and `/opt/kafka/external.advertised.listeners` in kafka pod?
the two files is not existed in kafka pod when my kafka installed done.

from line#95 to line#110 in https://github.com/kudobuilder/operators/blob/master/repository/kafka/operator/templates/bootstrap.yaml
it read configurations `ADVERTISED_LISTENERS` and `LISTENERS` from the two files I mentioned above, but get nothing because the two are not exists in pod.

I think it's the reason why the config file `server.properties` is missing my required settings advertised.listeners and listeners about expose kafka cluster externally with NodePort.

**Comment by zmalik** [comment]
@walk1ng the logic is in the docker image https://github.com/mesosphere/kudo-kafka-operator/tree/master/images/kafka

and it works when there are external-ip attached to the service. can you please post the logs of any Kafka pod? specially the first few lines when its trying to detect the service's external-ip

>Cloud i fix it by get the ip value use "internal ip" ? in private network in company, internal ip is safe and accessible too.

It would work with any IP that the kubelet gets assigned. Please read https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/#ways-to-connect 
Kafka or any other operator cannot do much here if the cluster isn't accessible.

**Comment by zmalik** [comment]
@walk1ng closing this issue as advertised.listeners is working with EXTERNAL_INGRESS when kubelets have external IP addresses.
