### ISSUE TITLE
Cassandra Grafana dashboard link broken

### ISSUE THREAD

**Issue by tbaums** [kudobuilder/frameworks#270]
Link to Grafana dashboard yields 404.

Line 74 - https://github.com/kudobuilder/operators/blob/master/repository/cassandra/3.11/docs/monitoring.md

**Comment by mpereira** [comment]
This would ideally be fixed in the KUDO C* [`create_operators_pull_request.py` script](https://github.com/mesosphere/kudo-cassandra-operator/blob/a061b2fe7c25567a433659436f0127102bf45f63/tools/create_operators_pull_request.py#L206-L216).

**Comment by mpereira** [comment]
(The link works there: https://github.com/mesosphere/kudo-cassandra-operator/tree/master/monitoring/grafana)

**Comment by zmalik** [comment]
added the fix here https://github.com/mesosphere/kudo-cassandra-operator/pull/141

**Comment by zmalik** [comment]
this is fixed now https://github.com/kudobuilder/operators/blob/master/repository/cassandra/3.11/docs/monitoring.md#2-install-the-grafana-dashboard
