### ISSUE TITLE
Kafka updating properties doesn't work

### ISSUE THREAD

**Issue by helli0n** [kudobuilder/frameworks#296]
When I tried to enable external access on minikube I've got error in kafka console 

`INFO[0000] Running kafka-utils...                       
INFO[0000] kubeconfig file: using InClusterConfig.      
INFO[0000] kubernetes client configured.                
INFO[0000] Running kafka-utils...                       
INFO[0000] Checking the service created for kafka-kafka-0 
INFO[0000] detected  NodePort                           
ERRO[0000] could not run the kafka utils bootstrap: no node found with name 'minikube' `

I checked nodes in k8s. k8s has minikube node

`kubectl get nodes --show-labels
NAME       STATUS   ROLES    AGE   VERSION   LABELS
minikube   Ready    master   44h   v1.19.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=minikube,kubernetes.io/os=linux,minikube.k8s.io/commit=1fd1f67f338cbab4b3e5a6e4c71c551f522ca138,minikube.k8s.io/name=minikube,minikube.k8s.io/updated_at=2020_09_30T16_32_03_0700,minikube.k8s.io/version=v1.13.1,node-role.kubernetes.io/master=`

Tried to debug kafka-utils but didn't find documentations and etc.
Do you have guide how to use kafka-utils?

**Comment by zmalik** [comment]
@helli0n thanks for filing the issue, Kafka operator is maintained in https://github.com/mesosphere/kudo-kafka-operator.

kafka-utils try to detect external-ip, can you check if minikube node has any external-ip? if there is no external-ip, you cannot enable external access using nodeports. 

The error message is misleading and should be fixed.

**Comment by helli0n** [comment]
Here is IP that minikube has. 
```
$ minikube ip
192.168.99.101
```

**Comment by zmalik** [comment]
not this one
can you please check using `kubectl get nodes -o wide` ? you will see a column of `EXTERNAL-IP`

**Comment by helli0n** [comment]
Sure, here is. I see that `EXTERNAL-IP:<none>`

> $ kubectl get nodes -o wide
> NAME       STATUS   ROLES    AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE               KERNEL-VERSION   CONTAINER-RUNTIME
> minikube   Ready    master   46m   v1.19.2   192.168.99.101   none       Buildroot 2019.02.11   4.19.114         docker://19.3.12

I will try to find how to add it.

**Comment by helli0n** [comment]
Looks like minikube hasn't EXTERNAL-IP. 
I think kafka-utils should be modified with adding additional check when operator was deployed on minikube. 
 
If local deploy then use INTERNAL-IP. 

https://github.com/mesosphere/kudo-kafka-operator/blob/master/images/kafka/kafka-utils/pkgs/service/service.go#L192-L203

**Comment by zmalik** [comment]
SGTM! can you create an issue in  https://github.com/mesosphere/kudo-kafka-operator repository? 

will take a look during the next week.
contributions are also welcome! 🙂

**Comment by helli0n** [comment]
https://github.com/mesosphere/kudo-kafka-operator/issues/63 - created ticket into Kafka operator repo
