### ISSUE TITLE
Document how to trigger an operator release

### ISSUE THREAD

**Issue by zmalik** [kudobuilder/frameworks#42]
Right now when doing an operator release, it's a manual process i.e. asking KUDO engineers to do a release of an operator.

We should document how operator developers can actually kickstart a release process for their operator.

**Comment by alenkacz** [comment]
I think you're working on this as part of contributing.md right @zmalik ?

**Comment by zmalik** [comment]
that won't document how the release is done but points to different mechanisms available right now for having a release

**Comment by alenkacz** [comment]
oh is this meant as an internal documentation for the core team?

**Comment by nfnt** [comment]
This is now implemented by CI/CD in https://github.com/kudobuilder/operators-index.
