### ISSUE TITLE
Change uses of .k8s.io to .kudo.dev

### ISSUE THREAD

**Issue by bgrant0607** [kudobuilder/frameworks#49]
The .k8s.io suffix is reserved for use by the Kubernetes project. Please change your API groups, labels, and annotations to use a domain that you own, such as .kudo.dev.

Work is underway to prevent accidental misuse in the apiserver:
https://github.com/kubernetes/enhancements/pull/1111

We are also adding more easily discoverable documentation regarding this.

Thanks.

**Comment by gerred** [comment]
Thanks @bgrant0607! These CRDs are out of date anyway and should be pointed at kudo.dev, these won't work in the most recent KUDO release anyway!
