### ISSUE TITLE
Can't deploy Kafka 0.1.1 with KUDO controller 0.5.0

### ISSUE THREAD

**Issue by djannot** [kudobuilder/frameworks#68]
I wan't to test the upgrade from one version of the Kafka Operator (0.1.1) to another (0.2.0), but the deployment of the version 0.1.1 doesn't work.
I can deploy the version 0.2.0 without any issue.

**Comment by alenkacz** [comment]
I think @zmalik found out yesterday during the demos the same thing. He's on PTO but he'll address next week I am sure

**Comment by zmalik** [comment]
we will do a new release for KUDO Kafka `0.1.2` with correct service labels so Kafka version 2.2.1 can work without any issues with latest KUDO release.

**Comment by zmalik** [comment]
@kensipe released `0.1.2` with correct labels and we have removed the `0.1.1` from the repository
