### ISSUE TITLE
ci test-4 failing

### ISSUE THREAD

**Issue by realmbgl** [kudobuilder/frameworks#73]
Ran into this with my elastic pull request. Alena restarted and then it worked. Just logging this to keep track in case we see this again.

https://circleci.com/gh/kudobuilder/operators/593

**Comment by alenkacz** [comment]
Fo some reason only 2/3 replicas were deployed in time :/ any ideas @jbarrick-mesosphere

**Comment by oliviabarrick** [comment]
I believe the correct thing to do is increase the timeout in the test: https://kudo.dev/docs/testing/reference.html#testassert
