### ISSUE TITLE
Some Operator yamls missing specifying namespace 

### ISSUE THREAD

**Issue by sarjeet2013** [kudobuilder/frameworks#89]
On checking the quick-start deployment for kafka, observed that the templates for kafka missing the namespace (`namespace: {{ .Namespace }}`) from some of the yamls. Also, observed this on other operator manifest yamls as well. 

See below example where namespace is missing from `Service` Yaml, but exists in `Statefulsets` Yaml

Statefulsets: https://github.com/kudobuilder/operators/blob/master/repository/kafka/operator/templates/statefulset.yaml#L5

Service: https://github.com/kudobuilder/operators/blob/master/repository/kafka/operator/templates/service.yaml#L4

**Comment by sarjeet2013** [comment]
@gerred FYI

**Comment by zmalik** [comment]
added it to all `kafka` resources
