### ISSUE TITLE
[Framework] MySQL

### ISSUE THREAD

**Issue by fabianbaier** [kudobuilder/frameworks#9]
It would be great to have https://github.com/kudobuilder/kudo/blob/master/config/samples/mysql.yaml as a standalone framework.

**Comment by yankcrime** [comment]
I was just looking at separating this example out and dropping it into the incubating frameworks folder, and then updating [the example](https://kudo.dev/docs/examples/backups/) accordingly.  I imagine that this would then be a more appropriate place to iterate on it.

**Comment by fabianbaier** [comment]
Sgtm plus this would also help with https://github.com/kudobuilder/kudo/issues/142 by having the `mysql.yaml` living here
